### ISSUE TITLE
Type issues when building on 32bit architectures

### ISSUE THREAD

**Issue by tillea** [cmayer/BaitFisher-package#7]
Hi,
the BaitFisher Debian package received a [bug report](https://bugs.debian.org/852839).  The report contains some [hints](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852839#17) and questions about the code.  It would be great if you could address this to make BaitFisher more portable.
Kind regards, Andreas.

**Comment by cmayer** [comment]
Has been fixed. Thanks!

One of the questions was why I reimplemented the string class. The reason was that
some years ago I checked the performance of the standard string class and it was really
bad compared to static or dynamic arrays. It was a factor of 3 and more slower than static arrays. If strings could grow very large it was even worse.
Since some of my Bioinformatic programs mainly work with strings I decided to implement this
string class. In view of these comments I checked the performance of todays implementations of the standard string class using todays compilers and the differences I saw a few years ago have vanished.
